### ISSUE TITLE
angular 开启自动保存api会导致http响应出现两次

### ISSUE THREAD

**Issue by gas0324** [lzwme/simple-mock#2]
开启isAutoSaveApi
每个接口首次请求响应内容会重复出现
例如：
{"fail":false,"code":"000000","data":{"cRelationStaff":"1346022894726664194","cUserStatus":0,"cUserUuid":"1346022697246248961","cUserType":0,"cAccountUuid":"1231231230123123123","cIdentityUuid":"1111222233334444555","cUniqueId":"123456guoanshang","cMobile":"18766005679"},"success":true,"time":"2021-04-21T05:35:53.646Z","mesg":"处理成功"}{"fail":false,"code":"000000","data":{"cRelationStaff":"1346022894726664194","cUserStatus":0,"cUserUuid":"1346022697246248961","cUserType":0,"cAccountUuid":"1231231230123123123","cIdentityUuid":"1111222233334444555","cUniqueId":"123456guoanshang","cMobile":"18766005679"},"success":true,"time":"2021-04-21T05:35:53.646Z","mesg":"处理成功"}

**Comment by renxia** [comment]
可以提供一下具体的截图，如关键使用的配置代码、接口请求的 network 情况等来分析一下

**Comment by gas0324** [comment]
### 配置文件
![图1](https://ae01.alicdn.com/kf/U6651abe13f02474b83eb2a42473e11387.jpg)
![图2](https://ae01.alicdn.com/kf/Ue3aa6790275e4eb58d46765e88fa0ad9W.jpg)


### 接口请求
![图3](https://ae01.alicdn.com/kf/U518b8ee3743648a28f724cbc09ccd355M.jpg)
![图4](https://ae01.alicdn.com/kf/U7413748d3b374ff98a9eff71a1e90ec8M.jpg)
![图5](https://ae01.alicdn.com/kf/Uf1d00c298d5140b78ecb30bde6598ec8i.jpg)
![图6](https://ae01.alicdn.com/kf/Uee9500bd391c420a9eac902bc41c617fP.jpg)

**Comment by renxia** [comment]
在本地调试，以及多个项目中测试，均为遇到你这种问题
可以试着在 `proxyRes` 事件、saveApi 调用等地方打印一些参数出来比对一下

另外可以看一下 `content-encoding` 的值，如果是空的，那么可以试着这么来写：

```js
onProxyRes(proxyRes, req, res) {
    const encoding = proxyRes.headers['content-encoding'];

    if (['gzip', '‘deflate'].includes(encoding)) {
      apiMock.saveApi(req, res, encoding);
    } else {
      const bufs = [];

      proxyRes.on('data', (data) => bufs.push(data));
      proxyRes.on('end', () => {
        let body = Buffer.concat(bufs).toString();
        res.end(body);

        try {
          body = JSON.parse(body);
        } catch (err) {}
        console.log(chalk.bgBlueBright('PROXYRES CONTENT: '), body);
        apiMock.saveApi(req, body, 'decoded');
      });
    }
 },
```

**Comment by gas0324** [comment]
按照您的方法进行测试，content-encoding的值的确是空的，尝试上面的写法，问题依旧，不知道您是否能安排时间远程确认一下我的环境？

**Comment by renxia** [comment]
你在上面示例中的 `res.end(body)` 这里打印一下 body 的值，看看是否已经被修改了；
或者尝试移除该行是否正常

**Comment by gas0324** [comment]
打印的body值正常
注释res.end(body)后，首次测试问题依旧存在，之后测试无问题，很疑惑，日后使用中我会继续注意该问题，感谢您的耐心回复

**Comment by renxia** [comment]
问题的原因已基本确定，刚做了相关逻辑更新，请使用 `1.4.2` 版本试试

**Comment by gas0324** [comment]
已更新，正在使用
